# Etapa de construcción
FROM node:23-alpine as build-stage
WORKDIR /app

# Copiar archivos de package para instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Compilar la aplicación para producción; esto generará una carpeta "dist"
RUN npm run build

# Etapa de producción
FROM nginx:stable-alpine as production-stage
# Copiar los archivos compilados al directorio de Nginx para servirlos
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Exponer el puerto 80 para acceder a la app
EXPOSE 80

# Comando para iniciar Nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]
